const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const upstream = b.dependency("libreadline", .{});
    const upstream_root = upstream.path(".");

    const mod = b.createModule(.{
        .optimize = optimize,
        .target = target,
        .link_libc = true,
    });

    const lib = b.addLibrary(.{
        .name = "readline",
        .linkage = .static,
        .root_module = mod,
    });
    mod.addIncludePath(upstream_root);
    mod.linkSystemLibrary("ncurses", .{});

    mod.addCSourceFiles(.{
        .root = upstream_root,
        .files = &.{
            "bind.c",
            "callback.c",
            "colors.c",
            "compat.c",
            "complete.c",
            "display.c",
            "funmap.c",
            "histexpand.c",
            "histfile.c",
            "history.c",
            "histsearch.c",
            "input.c",
            "isearch.c",
            "keymaps.c",
            "kill.c",
            "macro.c",
            "mbutil.c",
            "misc.c",
            "nls.c",
            "parens.c",
            "parse-colors.c",
            "readline.c",
            "rltty.c",
            "search.c",
            "shell.c",
            "signals.c",
            "terminal.c",
            "text.c",
            "tilde.c",
            "undo.c",
            "util.c",
            "vi_mode.c",
            "xfree.c",
            "xmalloc.c",
        },
        .flags = &.{
            "-DHAVE_UNISTD_H",
            "-DHAVE_STDLIB_H",
            "-DHAVE_STRING_H",
            "-DHAVE_STRINGS_H",
            "-DHAVE_DIRENT_H",
            "-DHAVE_FCNTL_H",
            "-DHAVE_WCHAR_H",
            "-DHAVE_WCTYPE_H",
            "-DHAVE_LOCALE_H",
            "-DHAVE_LIMITS_H",
            "-DHAVE_STDARG_H",
            "-DHAVE_STDBOOL_H",
            "-DHAVE_SYS_IOCTL_H",
            "-DHAVE_SYS_TIME_H",
            "-DHAVE_SYS_SELECT_H",
            "-DHAVE_TERMIOS_H",
            "-DHAVE_PWD_H",
            "-DHAVE_LANGINFO_H",
            "-DHAVE_MEMORY_H",
            "-DHAVE_CHOWN",
            "-DHAVE_FCNTL",
            "-DHAVE_FNMATCH",
            "-DHAVE_GETPWENT",
            "-DHAVE_GETPWNAM",
            "-DHAVE_GETPWUID",
            "-DHAVE_GETTIMEOFDAY",
            "-DHAVE_ISASCII",
            "-DHAVE_KILL",
            "-DHAVE_LSTAT",
            "-DHAVE_MBRLEN",
            "-DHAVE_MBRTOWC",
            "-DHAVE_MEMMOVE",
            "-DHAVE_PSELECT",
            "-DHAVE_PUTENV",
            "-DHAVE_READLINK",
            "-DHAVE_SELECT",
            "-DHAVE_SETENV",
            "-DHAVE_SETITIMER",
            "-DHAVE_SETLOCALE",
            "-DHAVE_STRCASECMP",
            "-DHAVE_STRCOLL",
            "-DHAVE_STRPBRK",
            "-DHAVE_SYSCONF",
            "-DHAVE_TCGETATTR",
            "-DHAVE_VSNPRINTF",
            "-DHAVE_WCRTOMB",
            "-DHAVE_WCSCOLL",
            "-DHAVE_WCSLEN",
            "-DHAVE_WCSNLEN",
            "-DHAVE_WCSNRTOMBS",
            "-DHAVE_WCTYPE",
            "-DHAVE_WCWIDTH",
            "-DHAVE_MBSTATE_T",
            "-DHAVE_WCHAR_T",
            "-DHAVE_WCTYPE_T",
            "-DHAVE_WINT_T",
            "-DHAVE_ISWCTYPE",
            "-DHAVE_ISWLOWER",
            "-DHAVE_ISWUPPER",
            "-DHAVE_TOWLOWER",
            "-DHAVE_TOWUPPER",
            "-DHAVE_LANGINFO_CODESET",
            "-DHAVE_POSIX_SIGNALS",
            "-DHAVE_POSIX_SIGSETJMP",
            "-DGWINSZ_IN_SYS_IOCTL",
            "-DSTRUCT_WINSIZE_IN_TERMIOS",
            "-DHAVE_GETPW_DECLS",
            "-DHAVE_STRUCT_DIRENT_D_INO",
            "-DHAVE_STRUCT_DIRENT_D_FILENO",
            "-DREADLINE_LIBRARY",
            "-D_POSIX_VERSION 200112L",
            "-DHAVE_TIMEVAL",
        },
    });

    lib.installHeadersDirectory(upstream_root, "", .{
        .include_extensions = &.{
            "readline.h",
            "history.h",
            "tilde.h",
            "chardefs.h",
            "keymaps.h",
        },
    });
    b.installArtifact(lib);
}
